import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/app/components/Navbar'

const font = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Shopping List',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={font.className}>
        {children}
        <Navbar />
        </body>
        </html>
    )
}
